### ISSUE TITLE
Fold in more planned upstream changes

### ISSUE THREAD

**Issue by Yawning** [oasisprotocol/ed25519#11]
In keeping with the "drop-in replacement" design goal, there are additional forthcoming upstream changes that need to be folded in.

 * [x] proposal: x/crypto/curve25519: new X25519 API (golang/go/issues/32670)
 * [x] crypto/ed25519: reject low order points (golang/go/issues/31846)
 * [x] crypto/ed25519: Implement Ed25519ph (golang/go/issues/31804)
 * [x] crypto: add Equal(PublicKey) bool method to PublicKey implementations (golang/go/issues/21704)

32670 includes the RFC 8422 check for contributory behavior.  There's some dissenting opinions about how useful this is (See section 12 of the Noise protocol spec for one).

The second issue, despite it's title at the time of this writing, applies to doing the appropriate checks in the ed25519 code.

These should wait till the relevant changes are merged upstream, support for ed25519ctx/ph was merged early because we were thinking about using it.

**Comment by Yawning** [comment]
We now reject low order points at verification time unless configured otherwise.  Calling this done.
